[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
